/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'off', // Light mode only, per architecture_review.md
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Core design tokens
        canvas: '#fbf9f3',
        surface: '#fbf9f3',
        'surface-bright': '#fbf9f3',
        'surface-dim': '#dcdad4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ed',
        'surface-container': '#f0eee8',
        'surface-container-high': '#eae8e2',
        'surface-container-highest': '#e4e2dc',
        'surface-variant': '#e4e2dc',
        'surface-tint': '#5f5e5b',

        primary: '#0e0f0c',
        'on-primary': '#ffffff',
        'primary-container': '#242421',
        'on-primary-container': '#8c8b87',
        'primary-fixed': '#e5e2dd',
        'primary-fixed-dim': '#c8c6c1',
        'on-primary-fixed': '#1c1c19',
        'on-primary-fixed-variant': '#474743',

        secondary: '#556159',
        'on-secondary': '#ffffff',
        'secondary-container': '#d8e6db',
        'on-secondary-container': '#5b675f',
        'secondary-fixed': '#d8e6db',
        'secondary-fixed-dim': '#bccabf',
        'on-secondary-fixed': '#121e17',
        'on-secondary-fixed-variant': '#3d4a42',

        tertiary: '#100f09',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#26241e',
        'on-tertiary-container': '#8f8b82',
        'tertiary-fixed': '#e8e2d8',
        'tertiary-fixed-dim': '#cbc6bd',
        'on-tertiary-fixed': '#1d1b16',
        'on-tertiary-fixed-variant': '#494640',

        'on-surface': '#1b1c18',
        'on-surface-variant': '#474741',
        'inverse-surface': '#30312d',
        'inverse-on-surface': '#f3f1eb',
        'inverse-primary': '#c8c6c1',
        'on-background': '#1b1c18',
        background: '#fbf9f3',

        outline: '#787770',
        'outline-variant': '#c8c7be',

        ink: '#242421',
        stone: '#b9b4ab',
        accent: '#66736a',
      },
      fontFamily: {
        display: ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        body: ['var(--font-literata)', 'Literata', 'serif'],
        label: ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-xl': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'display-lg': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'display-lg-mobile': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'headline-md': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'body-lg': ['var(--font-literata)', 'Literata', 'serif'],
        'body-md': ['var(--font-literata)', 'Literata', 'serif'],
        'nav-link': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'nav-link': ['13px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
      },
      spacing: {
        unit: '4px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        gutter: '24px',
        'section-gap': '120px',
      },
    },
  },
  plugins: [],
};